version = "3.7.14"
runner.dialect = scala213
docstrings.style = Asterisk
docstrings.wrap = false
maxColumn = 30
continuationIndent.defnSite = 2
assumeStandardLibraryStripMargin = true
rewrite.rules = [SortImports, RedundantBraces, RedundantParens, SortModifiers]

project {
    includePaths = [
        "glob:**/app/**/FormatThis.scala",
    ]
    excludePaths = [
        "glob:**/app/**/DontFormatThis.scala"
    ]
}

