load("@apple_rules_lint//lint:defs.bzl", "package_lint_config")
load("@contrib_rules_jvm//java:defs.bzl", "checkstyle_binary", "checkstyle_config", "java_junit5_test", "java_library", "java_test")
load("//:checkstyle.bzl", "checkstyle_config_wrapped")

checkstyle_binary(
    name = "checkstyle_bin",
    visibility = ["//visibility:public"],
    runtime_deps = ["@maven//:com_puppycrawl_tools_checkstyle"],
)

checkstyle_config(
    name = "my_checkstyle_config",
    checkstyle_binary = ":checkstyle_bin",
    config_file = "checkstyle.xml",
    #    output_format = "xml",
    visibility = ["//visibility:public"],
)

package_lint_config({
    "java-checkstyle": "//:my_checkstyle_config",
})

java_library(
    name = "entrypoint",
    srcs = ["src/main/java/com/example/EntryPoint.java"],
    data = glob(["src/main/resources/**"]),
    resources = glob(["src/main/resources/**"]),
)

java_junit5_test(
    name = "entrypoint_test",
    srcs = [
        "src/main/java/com/example/EntryPointTest.java",
    ],
    test_class = "main.java.com.example.EntryPointTest",
    runtime_deps = [
        ":entrypoint",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
    deps = [
        "@maven//:org_junit_jupiter_junit_jupiter_api",
    ],
)
