load("@contrib_rules_jvm//java:defs.bzl", "java_export", "java_library")

java_export(
    name = "app",
    srcs = ["src/main/java/com/example/EntryPoint.java"],
    data = glob(["src/main/resources/**"]),
    maven_coordinates = "com.example.vinnybod:app:0.0.1",
    deps = [
        "//lib",
    ],
)
