load("@contrib_rules_jvm//java:defs.bzl", "java_export", "java_library")

java_export(
    name = "lib",
    srcs = ["src/main/java/com/example/Library.java"],
    maven_coordinates = "com.example.vinnybod:library:0.0.1",
    resources = glob(["src/main/resources/**"]) + [
        "//:COPYRIGHT",
        #        "//:LICENSE",
    ],
    visibility = ["//visibility:public"],
)

# Swap this in to see the difference in behavior.
#java_library(
#    name = "lib",
#    srcs = ["src/main/java/com/example/Library.java"],
#    resources = glob(["src/main/resources/**"]) + [
#        "//:COPYRIGHT",
#        #        "//:LICENSE",
#    ],
#    visibility = ["//visibility:public"],
#)
