load("@aspect_rules_lint//format:defs.bzl", "format_multirun", "format_test")
load("@rules_java//java:defs.bzl", "java_binary")

java_binary(
    name = "scalafmt",
    data = ["//:.scalafmt.conf"],
    main_class = "org.scalafmt.cli.Cli",
    runtime_deps = ["@maven//:org_scalameta_scalafmt_cli_2_13"],
)

format_multirun(
    name = "format",
    scala = ":scalafmt",
    visibility = ["//:__subpackages__"],
)

format_test(
    name = "format_test",
    size = "small",
    no_sandbox = True,  # Enables formatting the entire workspace, paired with 'workspace' attribute
    scala = ":scalafmt",
    visibility = ["//:__subpackages__"],
    workspace = "//:README.md",  # A file in the workspace root, where the no_sandbox mode will run the formatter
)
